PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of you package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = mini_http mini_ifconfig l4lx_flips svtest flipsterm # idltest testbed

include $(L4DIR)/mk/subdir.mk


