# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# no special role
include $(L4DIR)/mk/Makeconf	

# cleanup
scrub cleanall::
	$(VERBOSE)$(RM) *~

# dummies
all clean install oldconfig txtconfig reloc::
