PKGDIR	?= ../../..
L4DIR	?= $(PKGDIR)/../..

SYSTEMS	= x86-l4v2 x86-l4x0
MODE	= l4env_base
TARGET	= libdiet_be_buddy_slab_mem.o.a
SRC_C_libdiet_be_buddy_slab_mem.o.a = buddy.c malloc.c

include $(L4DIR)/mk/lib.mk
