#! /bin/sh

# global settings
espenckey=0x54f11985_0594ceea_3d37893a_6be34b67_f31eab0d_86e4f0dc
espauthkey=0xc7b5fa7a_132f0868_d9dd39cb_6607fe35
algo=3des-md5-96
spi=0x200 
proto=tun
ipsecdev=ipsec0
privnet=10.1.0.0/24


# --- USAGE PRINTOUT ---
usage() {
	echo "Usage: setup_ipsec <gw|praseodym>"
	echo
}

# --- CLEANUP CONFIGURATIONS ---
#
# needs: physdev, ipsecdev
cleanup() {
	echo "cleaning up ipsec for ($physdev)"

	ip link set down $ipsecdev
	rmmod ipsec
}

# --- CONFIGURE TUNNEL, SPIs AND SPIGRPs ---
#
# needs: physdev, ipsecdev, esrc, edst
cfg_spi() {
	echo "set up ipsec for ($physdev)"
	modprobe ipsec

	ipsec tncfg --attach --virtual $ipsecdev --physical $physdev

	# inbound
	ipsec spi --esp $algo --said esp$spi@$esrc --enckey $espenckey --authkey $espauthkey --src $edst
	ipsec spi --ip4 --said tun$spi@$esrc --src $edst --dst $esrc
	ipsec spigrp --said tun$spi@$esrc esp$spi@$esrc

	# outbound
	ipsec spi --esp $algo --said esp$spi@$edst --enckey $espenckey --authkey $espauthkey --src $esrc
	ipsec spi --ip4 --said tun$spi@$edst --src $esrc --dst $edst
	ipsec spigrp --said tun$spi@$edst esp$spi@$edst

	ipsec eroute --add --eraf inet --src $esrc/32 --dst $edst/32 --said tun$spi@$edst
	ipsec eroute --add --eraf inet --src $privnet --dst $privnet --said tun$spi@$edst
}

# --- MAIN ---
case "$1" in
	gw)
		physdev=eth1
		esrc=10.0.0.1
		edst=10.0.0.59

		if [ "$2" == "cleanup" ]; then
			echo 0 > /proc/sys/net/ipv4/conf/eth0/proxy_arp
			cleanup
			exit 0
		fi

		cfg_spi

		ip address add 10.1.0.1 dev $ipsecdev
		ip link set up $ipsecdev

		# route to remote client
		ip route add 10.1.0.59/32 dev $ipsecdev
		# proxy arp for local clients
		echo 1 > /proc/sys/net/ipv4/conf/eth0/proxy_arp

		;;
	praseodym)
		physdev=eth1
		esrc=10.0.0.59
		edst=10.0.0.1

		if [ "$2" == "cleanup" ]; then
			cleanup
			exit 0
		fi

		cfg_spi

		ip address add 10.1.0.59 dev $ipsecdev
		ip link set up $ipsecdev

		# route to remote private network
		ip route add 10.1.0.0/24 dev $ipsecdev

		;;
	*)
		usage
		exit 1
		;;
esac
