#! /bin/bash

. ${0%/*}/generic.inc

[ -n "$UXRES"    ] || UXRES=800x600@16
ENABLE_NET=y

fiasco -N -m128 \
	-G $UXRES \
	-n10 -n11 -n12 -n13		\
	-l log				\
	-l dm_phys			\
	-l l4io				\
	-l names			\
	-l simple_ts			\
	-l rtc-ux			\
	-l ore_ux			\
	-l fuxfprov			\
        -l con-ux			\
	-l name_server			\
        -l fstab" -v132 -b/ -m/linux -v15 -b/ -m/anon_cfg" \
	-l flips-ore					\
	-l mini_ifconfig" -n eth0 192.168.2.4 255.255.255.0 192.168.2.1 -n lo 127.0.0.1 255.0.0.0" \
        -l "simple_file_server -v15"	\
           "-d$CFGPATH/config/mix1.xml"	\
           "-d$CFGPATH/config/mix2.xml"	\
           "-d$CFGPATH/config/mix3.xml"	\
	-l local_socks			\
	-l loader" $L4PATH/term_con $CFGPATH/mix.cfg"	\
	"$@"
