#! /bin/bash

#[ -n "$UXRES" ] || UXRES=640x480@16
#[ -n "$UXRES" ] || UXRES=320x240@16

. ${0%/*}/generic.inc

fiasco \
	-G $UXRES \
	-l names \
	-l log \
	-l dm_phys \
	-l l4io \
	-l con-ux \
	-l con_demo3 \
	-n9 "$@"
