#! /bin/bash

. ${0%/*}/generic.inc

fiasco \
	-G $UXRES \
	-l names \
	-l log \
	-l dm_phys \
	-l simple_ts \
	-l l4dope-ux \
	-l fuxfprov \
	-l loader \
    -l "name_server -e"\
    -l vc_server \
    -l vc_test \
    -l simple_file_server\
    -d "/home/mp26/boot/ascii/bambi_godzila Mr_Pumpkin" \
	-n9 "$@"\

