#! /bin/bash

. ${0%/*}/generic.inc

fiasco -tbuf_entries=32768 -jdb_cmd=I* \
        -G $UXRES                                                      \
        -l names                                                       \
        -l log                                                         \
        -l dm_phys                                                     \
        -l simple_ts                                                   \
        -l l4dope-ux                                                   \
        -l "fer_sensor_dir -v"                                         \
        -l fer_scalar_demo                                             \
        -l fer_histo_demo                                              \
        -l fer_list_demo                                               \
        -l fer_simple_mon                                              \
        -n9 "$@"
