#! /bin/bash
# This is a start script to run kaffe without java GUI and GUI (qt3 backend).
# Look also at run.sh in (l4/pkg/kaffe) example/javatest and example/awt. 

. ${0%/*}/generic.inc

[ -n "$UXRES"    ] || UXRES=800x600@16
[ -n "$L4DIR"    ] || L4DIR=${0%/*}/../..

# some properties for nonGUI and GUI version of kaffe
KAFFE_DIR="$L4DIR/pkg/kaffe"
FONTDIR="$L4DIR/pkg/qt3/lib/libqt3/lib/fonts"

if [ ! -e "$L4PATH/sfs_qt" ] && [ -n "$KAFFEGUI" ]; then
  echo ""
  echo "To use this script and L4 Kaffe + QT backend, a second"
  echo "simple_file_server (sfs_qt) instance is necessary !"
  echo ""
  echo "Please add in l4/pkg/l4vfs/simple_file_server/server/Makefile :"
  echo "  TARGET               += sfs_qt"
  echo "  DEFAULT_RELOC_sfs_qt  = 0x01380000"
  echo "and call make."
  exit 
fi

if [ -n "$KAFFEGUI" ]; then
  KAFFE_CFG="kaffe/qt.cfg"
  KAFFE_FSTAB="fstab -v132 -b/ -m/linux -c/qt3 -c/qt3/lib -c/qt3/lib/fonts
               -v14 -b/ -m/qt3/lib/fonts -v15 -b/ -m/kaffe"
  KAFFE_OPT="-l local_socks
             -l sfs_qt
             -d$FONTDIR/fontdir
             -d$FONTDIR/helvetica_100_50.qpf"
  KAFFE_JAR="-d$KAFFE_DIR/lib/l4kaffe/libraries/javalib/rt.jar
             -d$KAFFE_DIR/native/installation/jre/lib/kaffeawt.jar"
else
  KAFFE_CFG="kaffe/loader.cfg"
  KAFFE_FSTAB="fstab -v 132 -b/ -m/linux -v15 -b/ -m/kaffe"
  KAFFE_OPT=""
  KAFFE_JAR="-d$KAFFE_DIR/lib/l4kaffe/libraries/javalib/rt.jar"
fi

# simple_file_server has to provide:
#   - libloader.s.so
#   a loader script
#    - qt.cfg
#    - loader.cfg
#   - kaffevm
#   - rt.jar
#   with Java GUI
#    - kaffeawt.jar
#    QT Fonts
#   Java classes
#
#  optional:
#   - kaffepath.env

fiasco \
	-G $UXRES \
        -n8 \
        -l log \
        -l names \
        -l dm_phys \
        -l rtc-ux \
        -l simple_ts \
        -l con-ux \
        -l term_con \
        -l name_server \
        -l l4exec \
        -l "loader -fprov=fprov_proxy_fs $KAFFE_CFG" \
        -l fprov_proxy \
        -l "$KAFFE_FSTAB" \
            $KAFFE_OPT \
        -l "simple_file_server -v15"\
            $KAFFE_JAR \
           "-d$L4PATH/kaffevm" \
           "-d$L4PATH/libloader.s.so"  \
           "$@"
