#! /bin/bash

. ${0%/*}/generic.inc

KTEST=(ktest)

while [ -n "$1" ]; do
  case "$1" in
    -t)
       if [ -z "$testselection" ];
       then
         testselection=done
	 num=$2
	 shift
	 [ -z "$num" ] && num=1
	 KTEST=("ktest -t $num")
       fi
    ;;
    *)
       args="$args $1"
    ;;
  esac
  shift
done

fiasco -l "${KTEST[@]}" $args
