#! /bin/bash

. ${0%/*}/generic.inc

fiasco \
	-G $UXRES \
	-l names \
	-l log \
	-l dm_phys \
	-l l4io \
	-l l4dope \
	-l "fuxfprov --searchpath $L4PATH:$CFGPATH" \
	-l simple_ts \
        -l "name_server" \
	-l "loader rl_ex.cfg" \
	-n10 "$@"
