#! /bin/bash

[ -n "$UXRES" ] || UXRES=640x480@16

. ${0%/*}/generic.inc

RMGR_ARGS="task modname \"run\""

fiasco \
	-G $UXRES				\
	-l names\ --events			\
	-l log					\
	-l events				\
	-l dm_phys\ --events			\
	-l simple_ts\ --events			\
	-l fuxfprov -n10			\
	-l con-ux\ --events			\
	-l l4exec				\
	-l loader" --events $L4PATH/run"	\
	"$@"
