#! /bin/bash

# This is the runux script for the l4vfs term_con server test.
# The file specified below will be printed slowly to the terminal int the
# end of the test.  ASCII animations should work.

[ -n "$UXRES" ] || UXRES=800x600@32

. ${0%/*}/generic.inc

fiasco \
	-G $UXRES \
	-l names \
	-l log \
	-l dm_phys \
	-l l4io \
	-l con-ux \
	-l rtc-ux \
	-l "name_server -e" \
	-l simple_file_server \
	-d "/home/mp26/boot/ascii/bambi_godzila Mr_Pumpkin" \
	-l term_con \
	-l term_con_test \
	-n8 -n9 -n10 \
	"$@"
