PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= many_threads
MODE		= tiny
DEFAULT_RELOC	= 0x01000000
SYSTEMS		= x86-l4v2 amd64-l4v2 x86-l4secv2emu
SRC_C		= many_threads.c

include $(L4DIR)/mk/prog.mk
