PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of you package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = bmsic bmsi_test hello_test hello_test2 

include $(L4DIR)/mk/subdir.mk


