/**
 * This test demonstrates the different kinds to transmit
 * a string.
 */
interface test 
{
  void ein_string  ([in, string] char *str1);
  void zwei_string ([in, string] char *str1,
      [in, string] char *str2);
  void gib_string  ([in] long a,
      [in, string] char *instr,
      [out, string] char **outstr);
  void drei_string([in, string, max_is(256)] char* str);
  void vier_string([in, ref, string, max_is(256)] char* refstr);
  void fuenf_string([in, ref, string, max_is(100)] char* refstr2);
  
  struct dirent {
      long d_ino;
      long d_off;
      unsigned short d_reclen;
      char d_name[256]; /* We must not include limits.h! */
  };
  
  int getdents([in] long fd,
      [out, size_is(count), transmit_as(unsigned char),
      ref, prealloc] struct dirent * dirp,
      [in, out] unsigned int * count);
};

