PKGDIR  ?= ../../..
L4DIR   ?= $(PKGDIR)/../..

SYSTEMS  = x86-l4v2 x86-l4x0 arm-l4x0

TARGET   = libdiet_be_l4_start_stop.a

SRC_C    = _exit.c abort.c

MODE     = l4env_dietlibc_minimal

include $(L4DIR)/mk/lib.mk
