# directories we need to know
PKGDIR ?=	../../..
L4DIR ?=	$(PKGDIR)/../..

# source files
SERVERIDL =	blk.idl

# target
TARGET =	libgeneric_blk-server.a
SYSTEMS =	x86-l4v2

# include lib role
include $(L4DIR)/mk/lib.mk

