PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

IDL		= nh-cfg.idl nh-client.idl nh.idl
IDL_FLAGS	= -fctypes 
IDL_EXPORT_STUB     = %
IDL_EXPORT_SKELETON = %

SYSTEMS		= x86-l4v2 x86-l4x0


include $(L4DIR)/mk/idl.mk
