
PKGDIR         ?= ../../..
L4DIR          ?= $(PKGDIR)/../..
TARGET          = presenter_exec
#DEFAULT_RELOC   = 0x01800000
MODE		= l4linux
SRC_C		= server.c
SERVERIDL	= presenter_exec.idl

include $(L4DIR)/mk/prog.mk
