#!/bin/sh

# install default directory hierarchy and default Makefiles
#
# Call this script from a newly created package directory.

set -e

SRCDIR="${0%/*}"
TARGETDIR="`pwd`"
TOINSTALL="MAINTAINER Makefile idl include lib server examples doc"

for file in $TOINSTALL ; do
	cp -vir $SRCDIR/$file $TARGETDIR
done
