#!/bin/sh

# install default directory hierarchy and default Makefiles
#
# Call this script from a newly created package directory.

set -e

SRCDIR="${0%/*}"
TARGETDIR="`pwd`"
TOINSTALL="MAINTAINER Makefile idl include lib server examples doc ptest"

tar c -C $SRCDIR -f- --exclude=CVS $TOINSTALL | tar xvf -
