# directories we need to know
PKGDIR ?=       ../..
L4DIR ?=        $(PKGDIR)/../..

# source files
SRC_C =		slab.c
PRIVATE_INCDIR = ../../include

# targets
TARGET = 	libslab.a
MODE = 		l4env
SYSTEMS =	x86 arm
# include lib role
include $(L4DIR)/mk/lib.mk
