PKGDIR?= ../../..
L4DIR ?= $(PKGDIR)/../..

SYSTEMS		= x86-l4v2 x86-l4x0 arm-l4x0

# the name of your library
TARGET		= libdiet_be_minimal_io.a

# list your .c files here
SRC_C	= write.c lseek.c

MODE		= libc

#DEBUG		= 1

include $(L4DIR)/mk/lib.mk
