PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

IDL 		= dm_phys.idl
IDL_FLAGS	= -fl4types
IDL_EXPORT_SKELETON = dm_phys.idl
PRIVATE_INCDIR	= $(L4INCDIR)
SYSTEMS		= x86-l4v2 x86-l4x0 arm-l4x0

include $(L4DIR)/mk/idl.mk
