# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# source files
SRC_C =		main.c

# target
TARGET =	l4lload
SYSTEMS = 	x86-l4v2
MODE = 		l4linux
L4LIBS = 	

include $(L4DIR)/mk/prog.mk
