/*
 * This is an example interface for the sockets example.
 *
 * If you wish to use sockets as one of the communication method
 * you should be aware, that indirect string IPC and flexpages
 * cannot be transmitted. The generated stubs do not handle messages,
 * which are too big, which would require resending etc.
 *
 * Sockets can be generated using the -Bisock switch for Dice.
 * The generated code should be compiled with the defined
 * symbol SOCKETAPI, which lets the preprocessor include the
 * appropriate header files.
 */

typedef struct {
    long a;
    long b;
    union uni_C
      {
	long d;
	short e;
      } c;
} str_A;

interface sock_srv
{
  long func1([in] long a);
  long func2([out, string] char** str);

  void func3([in] str_A t);
  void func4([in, string] char* str,
      [in, string] char *str2);
  void func5([in, string, max_is(120)] char* str);
  long func6([in, string] char* str,
      [in, string] char *str2);
};
