PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= libcon.a
MODE		= l4env
SYSTEMS		= x86-l4v2 arm-l4v2 amd64-l4v2
SRC_C		= keymap.c
PRIVATE_INCDIR  = $(SRC_DIR)/../include
CLIENTIDL	= l4con.idl

include $(L4DIR)/mk/lib.mk
