/* 
 * These examples have been contributed by:
 * Andreas Haeberlen
 * haeberlen@ira.uka.de
 */

interface one
{
  long tiny(in long a);
};

interface two
{
  long small(in short a, in long b, in short c);
};

interface three
{
  long large(in long a, in long b, in long c, in long d, in long e, in long f);
};

interface four
{
  void strxfer(in string<119> a, out long b, out long c);
};

typedef struct
{
  long a[20];
  short b, c;
  char d, e[200];
  short f, g[80];
  long h, i;
  char j, k, l[20];
  struct m_tag
  {
    short n;
    char o;
    long p;
    short q, r;
  } m[2];
} large_t;

interface five
{
  long structxfer(in large_t a, out long b);
};

/*
 * This example only works with DCE parser, because of 
 * the [length_is] attribute. Since Dice does not allow
 * mixed IDL files (CORBA IDL and DCE IDL), we have to 
 * uncomment this example.
 * It also appears in the arrays example.
 *
interface six
{
  void arrayxfer([in, length_is(l1)] char* str1, 
  		 [in, length_is(l2)] char* str2,
		 [in] long l1, [in] long l2);
};
*/

