NOTARGETSTOINSTALL = 1

PKGDIR          ?= ../../..
L4DIR           ?= $(PKGDIR)/../..
SYSTEMS          = x86-l4v2 x86-l4x0
TARGET           = libpresenter_view.a

SRC_C	= display.c

PRIVATE_INCDIR  = $(PKGDIR)/server/include

include $(L4DIR)/mk/lib.mk
