#
# Makefile for ORe server lib
#

PKGDIR         ?= ../..
L4DIR          ?= $(PKGDIR)/../../..

SYSTEMS		= x86-l4v2

TARGET		= libore_server-worker.a

SERVERIDL	= worker.idl

include $(L4DIR)/mk/lib.mk
