PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..
SYSTEMS		= x86-l4v2
TARGET		= libl4exec.a
MODE		= l4env
SRC_C		= errstr-exec.c
CLIENTIDL	= exec.idl
SYSTEMS		= x86-l4v2 arm-l4x0
CPPFLAGS	= -DL4_MAX_RPC_BUFFER_SIZE=512

include $(L4DIR)/mk/lib.mk
