PKGDIR   ?= ../..
L4DIR    ?= $(PKGDIR)/../..

CLIENTIDL = rt_mon.idl
SRC_C     = comm.c

MODE      = l4env_minimal

SYSTEMS   = x86-l4v2 x86-l4x0

TARGET    = librt_mon_mon.a

include $(L4DIR)/mk/lib.mk
