#
# $Id$
#
# Makefile for the names demo
#

PKGDIR	= ..
L4DIR	?= $(PKGDIR)/../..

# do not include exit-Demo here, as it requires l4env
TARGET	= demo1 demo2 demo3 hello

include $(L4DIR)/mk/subdir.mk
