# directories we need to know
PKGDIR ?=       ../..
L4DIR ?=        $(PKGDIR)/../..

# source files
SRC_C =		libdsi.c dataspace.c packet.c socket.c sync.c thread.c \
		app.c jcp.c event.c select.c convenience.c error.c

PRIVATE_INCDIR = $(SRC_DIR)/../include

# target
TARGET =	libdsi.a
SYSTEMS =	x86-l4v2

# include lib role
include $(L4DIR)/mk/lib.mk


