PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

IDL 		= generic_io.idl
IDL_FLAGS	= -fl4types -fserver-parameter
SYSTEMS		= x86-l4v2 x86-l4x0
IDL_EXPORT_STUB = generic_io.idl
IDL_EXPORT_SKELETON = generic_io.idl

include $(L4DIR)/mk/idl.mk
