PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

IDL = generic_io.idl
SYSTEMS = x86-l4v2 amd64-l4v2 arm-l4v2
IDL_EXPORT_STUB = generic_io.idl
IDL_EXPORT_SKELETON = generic_io.idl
IDL_FLAGS = -fconst-as-define

include $(L4DIR)/mk/idl.mk
