/* $Id: $ */
/** \file generic_fprov/idl/generic_fprov.idl
 *  \date   22/08/2000
 *  \author Frank Mehnert <fm3@os.inf.tu-dresden.de>
 *  \brief Common L4 Environment, File provider interface
 */

import <l4/sys/types.h>
import <l4/dm_generic/types.h>

/** \brief module l4 */
library l4fprov
{
  /** File provider interface */
  interface file
    {
      /*! Open new binary and return a dataspace containing the binary image
       * of the file.
       * 
       *  \param fname	file name
       *  \param dm	id of dataspace manager to use
       *  \param flags	flags (currently unused)
       *  
       *  \retval ds	opened dataspace
       *  \retval size	size of file in bytes
       */
      long open([in, string] char* fname, 
                [in] l4_threadid_t dm, 
                [in] unsigned long flags,
                [out] l4dm_dataspace_t *ds, 
                [out] l4_size_t *size);
    };
};

