/* $Id: $ */
/** \file generic_fprov/idl/generic_fprov.idl
 *  \date   22/08/2000
 *  \author Frank Mehnert <fm3@os.inf.tu-dresden.de>
 *  \brief Common L4 Environment, File provider interface
 */

/** \brief module l4 */
module l4fprov
{
  struct threadid_t
    {
      unsigned long low;
      unsigned long high;
    };
  
  struct dataspace_t
    {
      unsigned long id;
      threadid_t manager;
    };
  
  /** File provider interface */
  interface file
    {
      /*! Open new binary and return a dataspace.
       * 
       *  \param fname	file name
       *  \param dm	id of dataspace manager to use
       *  \param flags	flags
       *  
       *  \retval ds	opened dataspace
       *  \retval size	size of file in bytes
       */
      long open(in string fname, in threadid_t dm, in unsigned long flags,
	        out dataspace_t ds, out unsigned long size);
    };
};

