/*
 * This file is distributed along with the 'dice' package. It contains
 * constants, types and functions needed by the code generated by dice.
 *
 */

#ifndef L4API_l4v2
#ifndef L4API_l4x0
#ifndef L4API_linux
#warning no L4 API set
#define L4API_l4v2
#endif // !linux
#endif // !L4X0
#endif // !L4V2

#ifdef L4API_linux
#include "dice/dice-sockets.h"
#else
#ifdef L4API_l4v2
#include "dice/dice-l4-v2.h"
#else
#ifdef L4API_l4x0
#include "dice/dice-l4-x0.h"
#endif // L4X0
#endif // L4V2
#endif // SOCKET

