PKGDIR    ?= ../../..
L4DIR     ?= $(PKGDIR)/../..

SYSTEMS	   = x86-l4v2 arm-l4v2 amd64-l4v2
TARGET     = liblog-buffer.a
CLIENTIDL  = buffer.idl
IDL_PKGDIR = $(PKGDIR_OBJ)/examples/logcon

include $(L4DIR)/mk/lib.mk
