PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = libl4env-l4lx.a
BUILD_PIC	= libl4env-l4lx.a
SYSTEMS         = x86-l4v2 arm-l4v2

SRC_C           = l4env-l4lx.c

PRIVATE_INCDIR	= $(SRC_DIR)

include $(L4DIR)/mk/lib.mk
