# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# target
TARGET =	libdsiexmpl_filter.a
SYSTEMS =	x86-l4v2

# source files
SRC_C = 	libfilter.c
CLIENTIDL =	filter.idl

# include lib role
include $(L4DIR)/mk/lib.mk
