
PKGDIR         ?= ../../..
L4DIR          ?= $(PKGDIR)/../..
TARGET          = presenter_fprov
MODE		= l4linux
SRC_C		= server.c
SERVERIDL	= presenter_fprov.idl
LIBS		= -ldm_generic -ll4env-l4lx

include $(L4DIR)/mk/prog.mk
