PKGDIR    ?= ../..
L4DIR     ?= $(PKGDIR)/../..

TARGET    = libnitpicker-idl.a
MODE      = l4env
SYSTEMS   = x86-l4v2 arm-l4x0
CLIENTIDL = nitpicker.idl
SERVERIDL = nitevent.idl

include $(L4DIR)/mk/lib.mk
