PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

SYSTEMS  = x86-l4v2 arm-l4v2 amd64-l4v2
MODE     = l4env_minimal
TARGET   = libc_be_minimal_log_io.a
SRC_C    = write.c lseek.c

include $(L4DIR)/mk/lib.mk
