/* -*- c -*- */
/**
 * \file   l4vfs/idl/container_io.idl
 * \brief  
 *
 * \date   11/18/2004
 * \author Martin Pohlack  <mp26@os.inf.tu-dresden.de>
 */
/* (c) 2004 Technische Universitaet Dresden
 * This file is part of DROPS, which is distributed under the terms of the
 * GNU General Public License 2. Please see the COPYING file for details.
 */
import <l4/sys/types.h>
import <l4/l4vfs/types.h>

/**
 * @brief L4 virtual file system interface
 */
library l4vfs
{
    /**
     * @brief enable the creation of directories
     */
    [uuid(40)]
    interface container_io
    {
        /* The same naming rules as for creat() apply here.
         */
        int mkdir([in] object_id_t parent,
                  [in, string] char * name,
                  [in] l4vfs_mode_t mode);
    };
};
