/* -*- c -*- */ 
/**
 * \file   l4vfs/idl/network_server.idl
 * \brief  
 *
 * \date   11/18/2004
 * \author Martin Pohlack  <mp26@os.inf.tu-dresden.de>
 */
/* (c) 2004 Technische Universitaet Dresden
 * This file is part of DROPS, which is distributed under the terms of the
 * GNU General Public License 2. Please see the COPYING file for details.
 */
import <l4/sys/types.h>
import <l4/l4vfs/types.h>

import <l4/l4vfs/net_io.idl>
import <l4/l4vfs/connection.idl>

/**
 * @brief L4 virtual file system interface
 */
library l4vfs
{
    /**
     * @brief Usual interface for network servers
     */
    [uuid(1006)]
        interface network_server : net_io, connection
    {
    };
};
