PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

IDL 		= $(PKGNAME).idl
IDL_EXPORT_SKELETON = $(PKGNAME).idl
SYSTEMS		= x86-l4v2 arm-l4x0 amd64-l4v2
IDL_FLAGS	= -fforce-corba-alloc

include $(L4DIR)/mk/idl.mk
