PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

IDL 		= $(PKGNAME).idl
IDL_EXPORT_SKELETON = $(PKGNAME).idl
SYSTEMS		= x86-l4v2 x86-l4x0 arm-l4x0
IDL_FLAGS	= -fforce-corba-alloc -fl4types

include $(L4DIR)/mk/idl.mk
