PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

SYSTEMS = x86-l4v2 x86-l4x0
TARGET	= libomega0-emul.a
SRC_C	= emul.c

PRIVATE_INCDIR = $(PKGDIR)/server/include $(PKGDIR)/lib/include

include $(L4DIR)/mk/lib.mk
