/* -*- c -*- */
/* $Id$ */
/*****************************************************************************/
/**
 * \file   l4rm/idl/l4rm.idl 
 * \brief  Region mapper IPC interface. 
 *
 * \date   06/02/2000
 * \author Lars Reuther <reuther@os.inf.tu-dresden.de>
 */
/*****************************************************************************/

/* (c) 2003 Technische Universitaet Dresden
 * This file is part of DROPS, which is distributed under the terms of the
 * GNU General Public License 2. Please see the COPYING file for details.
 */

library l4
{
  [default_function(l4rm_handle_pagefault), uuid(0xd00)]
  interface rm
    {
      /* add entry to region tree */
      long add();

      /* remove entry region tree */
      long remove();
    };
};
