PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of you package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = l4_client name_server_client libc_io_client

include $(L4DIR)/mk/subdir.mk
