PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

SYSTEMS  = x86-l4v2 x86-l4x0

TARGET   = libl4vfs_name_server.a

SRC_C_libl4vfs_name_server.a = name_server.c

MODE     = l4env_minimal

include $(L4DIR)/mk/lib.mk
