SYSTEMS			:= 	x86-l4v2
PKGDIR			?=	../../..
L4DIR			?=	$(PKGDIR)/../..

TARGET			 =	libcr7libm.a

SRC_S			 =	acos.S atan.S ceil.S cosh.S cos.S exp.S floor.S __half.S log10.S log.S pow.S rint.S sinh.S sin.S sqrt.S tanh.S tan.S

include $(L4DIR)/mk/lib.mk


