PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

MODE_x86-l4v2	:= sigma0
MODE		:= libc
LIBCBACKEND_LIB :=
SRC_CC		:= init_eh_frame.cc
SYSTEMS		:= x86 arm
TARGET		:= libc++start.o.a

include $(L4DIR)/mk/lib.mk


