PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../../..

IDL 		= vcore_video.idl vcore_audio.idl
IDL_FLAGS =     -fl4types
SYSTEMS =       x86-l4v2

PRIVATE_INCDIR = $(PKGDIR)/../include $(PKGDIR)/../config

include $(L4DIR)/mk/idl.mk
