PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../../..

IDL 		= vcore_video.idl vcore_audio.idl
SYSTEMS =       x86-l4v2

PRIVATE_INCDIR = $(PKGDIR)/../include $(PKGDIR_OBJ)/../config

include $(L4DIR)/mk/idl.mk
