PKGDIR      ?= ../../..
L4DIR       ?= $(PKGDIR)/../..

TARGET      = libovlsrv-idl.a
MODE        = l4env
SYSTEMS     = x86-l4v2
CLIENTIDL   = input_listener.idl window_listener.idl
SERVERIDL   = overlay.idl

include $(L4DIR)/mk/lib.mk
