PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../..

EXPECTED_OUT = ../expected.txt

TEST_SERVER = dm_phys_test

SYSTEMS	= x86-l4v2

BASE_SERVERS = log names dm_phys events
MEMORY = 256
TIMEOUT = 60

include $(L4DIR)/mk/runux.mk
