
/*
 * These defines are the mangled function for the new
 * and destroy functions as generated by the GCC. They
 * depend on the compiler version.
 */
#define REAL_CXX_NEW  __real ## __Znwj
#define WRAP_CXX_NEW  __wrap ## __Znwj
#define REAL_CXX_FREE __real ## __ZdlPv
#define WRAP_CXX_FREE __wrap ## __ZdlPv


/* Generated by the linker using petze.mk */
extern void *__real_malloc (unsigned int size);
extern void *__real_calloc (unsigned int nmemb, unsigned int size);
extern void *__real_realloc(void *addr, unsigned int size);
extern void  __real_free   (void *addr);
extern void *REAL_CXX_NEW  (unsigned int size);
extern void  REAL_CXX_FREE (void *addr);


extern void *__wrap_malloc (unsigned int size);
extern void *__wrap_calloc (unsigned int nmemb, unsigned int size);
extern void *__wrap_realloc(void *addr, unsigned int size);
extern void  __wrap_free   (void *addr);
extern void *WRAP_CXX_NEW  (unsigned int size);
extern void  WRAP_CXX_FREE (void *addr);
