SYSTEMS         := x86-l4v2
PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET           = petze
DEFAULT_RELOC    = 0x00800000
SRC_C            = petze.c
SERVERIDL        = petze.idl

include $(L4DIR)/mk/prog.mk

