# directories we need to know
PKGDIR ?=       ..
L4DIR ?=        $(PKGDIR)/../..

# source files
IDL =		send.idl receive.idl filter.idl
SYSTEMS =	x86-l4v2

# include IDL role
include $(L4DIR)/mk/idl.mk
