# directories we need to know
PKGDIR ?=       ..
L4DIR ?=        $(PKGDIR)/../..

# source files
IDL =		send.idl receive.idl filter.idl
IDL_TYPE =	flick
SYSTEMS =	x86-l4v2 x86-l4x0

# include IDL role
include $(L4DIR)/mk/idl.mk
