/* -*- c -*- */
/* $Id$ */
/*****************************************************************************/
/**
 * \file  dsi_example/idl/receive/receive.idl
 * \brief Interface definition for receive component.
 *
 * \date   01/10/2001
 * \author Lars Reuther <reuther@os.inf.tu-dresden.de>
 */
/*****************************************************************************/

import <l4/sys/types.h>
  
typedef struct dsi_example_receive_socket
{
  unsigned long socket;
  l4_threadid_t work_th;
  l4_threadid_t sync_th;
  l4_threadid_t event_th;
} dsi_example_receive_socket_t;
  
typedef struct dsi_example_receive_dataspace
{
  unsigned long id;
  l4_threadid_t manager;
} dsi_example_receive_dataspace_t;

library dsi_example
{
  interface receive
    {
      /**
       * Open receive socket
       */
      long open([in] dsi_example_receive_dataspace_t ctrl_ds,
		[in] dsi_example_receive_dataspace_t data_ds,
		[out] dsi_example_receive_socket_t *s);

      /**
       * Connect with sender
       */
      long connect([in] dsi_example_receive_socket_t local,
		   [in] dsi_example_receive_socket_t remote);
    };
};
