/* -*- c -*- */
/* $Id$ */
/*****************************************************************************/
/**
 * \file  dsi_example/idl/send/send.idl
 * \brief Interface definition for send component.
 *
 * \date   01/10/2001
 * \author Lars Reuther <reuther@os.inf.tu-dresden.de>
 */
/*****************************************************************************/

import <l4/sys/types.h>
  
typedef struct dsi_example_send_socket
{
  unsigned long socket;
  l4_threadid_t work_th;
  l4_threadid_t sync_th;
  l4_threadid_t event_th;
} dsi_example_send_socket_t;
  
typedef struct dsi_example_send_dataspace
{
  unsigned long id;
  l4_threadid_t manager;
} dsi_example_send_dataspace_t;

library dsi_example
{
  interface send
    {
      /**
       * Open send socket 
       */
      long open([out] dsi_example_send_socket_t *s, 
		[out] dsi_example_send_dataspace_t *ctrl_ds,
		[out] dsi_example_send_dataspace_t *data_ds);

      /**
       * Connect with receiver
       */
      long connect([in] dsi_example_send_socket_t local, 
		   [in] dsi_example_send_socket_t remote);

      /**
       * Start
       */
      long start([in] dsi_example_send_socket_t local);

      /**
       * Stop
       */
      long stop([in] dsi_example_send_socket_t local);

      /**
       * Close
       */
      long close([in] dsi_example_send_socket_t local);
    };
};
