import <l4/sys/types.h>
#pragma force-include
#include <l4/ipreg/__ipreg.h>

interface ipreg {

        int register([in, string, max_is(IPREG_MAX_NAME_LEN)] char *name,
                     [in, string, max_is(IPREG_MAX_ADDR_LEN)] char *addr);

        int query(   [in,  string, max_is(IPREG_MAX_NAME_LEN)] char *name,
                     [out, string, max_is(IPREG_MAX_ADDR_LEN), prealloc_client] char **addr);
};
