# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# source files
SRC_C =		semaphore.c
PRIVATE_INCDIR = $(SRC_DIR)/../include

# target
TARGET = 	libsemaphore.a
SYSTEMS =	x86-l4v2 arm-l4x0 amd64-l4v2

# include lib role
include $(L4DIR)/mk/lib.mk



