# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# source files
SRC_C =		semaphore.c
PRIVATE_INCDIR = ../../include

# target
TARGET = 	libsemaphore.a
SYSTEMS =	x86-l4v2 x86-l4x0 arm-l4x0

# include lib role
include $(L4DIR)/mk/lib.mk



