PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = l4io_dummy
DEFAULT_RELOC   = 0x00900000
SYSTEMS         = x86-l4v2

LIBS            = -lio
SRC_C           = main.c

include $(L4DIR)/mk/prog.mk
