# directories we need to know
PKGDIR  = .
L4DIR  ?= $(PKGDIR)/../..

SUBDIRS = name_server term_server static_file_server simple_file_server fstab \
          fprov_proxy l4vfs_log

include $(L4DIR)/mk/subdir.mk
