PKGDIR  ?= ../../..
L4DIR   ?= $(PKGDIR)/../..

SYSTEMS  = x86-l4v2 x86-l4x0 arm-l4x0
TARGET   = libuc_be_minimal_io.a
SRC_C    = write.c lseek.c
MODE     = l4env_uclibc_minimal

include $(L4DIR)/mk/lib.mk
