SYSTEMS			:= x86-l4v2 
PKGDIR			?=	../../..
L4DIR			?=	$(PKGDIR)/../..

TARGET			 =	libmpeg2.a

SRC_C			 =	alloc.c cpu_state.c header.c idct_mmx.c motion_comp_mmx.c rgb_mmx.c uyvy.c \
				cpu_accel.c decode.c idct.c motion_comp.c rgb.c  slice.c

include $(L4DIR)/mk/lib.mk

