PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET	= libddekit.a

# list your .c files here
SRC_C	= condvar.c \
		  malloc.c \
		  init.c \
		  initcall.c \
		  interrupt.c \
		  lock.c \
		  memory.c \
		  panic.c \
		  pci.c \
		  pgtab.c \
		  printf.c \
		  resources.c \
		  semaphore.c \
		  thread.c \
		  timer.c

include $(L4DIR)/mk/lib.mk
