# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# target
TARGET =	libdsiexmpl_receive.a
SYSTEMS =	x86-l4v2

# source files
SRC_C = 	libreceive.c
CLIENTIDL =	receive.idl

# include lib role
include $(L4DIR)/mk/lib.mk
