PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = initcalldemo

SRC_CC          = main.cc
DEFAULT_RELOC	= 0x00400000
CXXFLAGS	= -fno-rtti -fno-exceptions

include $(L4DIR)/mk/prog.mk
