PKGDIR       ?= ../..
L4DIR        ?= $(PKGDIR)/../..
SYSTEMS       = x86-l4v2 x86-l4x0
IDL           = donsched.idl
IDL_FLAGS     = --message-passing -fno-server-loop -fno-dispatcher

include $(L4DIR)/mk/idl.mk

