/**
 * This is a simple test interface. The pronounciation is on "simple" ;)
 *
 * This interface only has a few functions sending simple scalar values.
 *
 */
interface simple
{
  /**
   * This function should be transmitted using a short IPC
   */
  void func1([in] int t1);
  /**
   * This function requires a long IPC.
   */
  void func2([in] int t1, [in] int t2, [in] int t3);
  /**
   * This function should also require a short IPC.
   * [out] parameters have to be referenced, because the compiler could do it
   * implicetly, but that would be no good for the user.
   */
  void func3([out] int *t1);
  /**
   * Should also require a long IPC
   */
  void func4([out] int *t1, [out] int *t2, [out] int *t3);
  /**
   * short IPC both ways
   */
  void func5([in] int t1, [out] int *t2);
  /**
   * also short IPC both ways
   * if using a return type, be aware that this is also data, which has to be transmitted
   */
  int func6([in] int t1);
  /**
   * references should be derederenced
   */
  void func7([in] int *t1);
};
