######################################################################
# Automatically generated by qmake (1.04a) Wed Dec 17 17:06:25 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += . ./english

# Input
HEADERS += english/lang.h config.h gamelib.h window.h wiese.h levels.h 
SOURCES += main.cpp gamelib.cpp window.cpp wiese.cpp levels.cpp
