PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../..
SYSTEMS       = x86-l4v2 x86-l4x0 x86-linux

IDL           = petze.idl
IDL_FLAGS     = -fserver-parameter -fforce-corba-alloc -fctypes

include $(L4DIR)/mk/idl.mk
