L4DIR	?= ../../..

TARGET	= simple_idl array_idl struct_idl struct2 \
	  corba_idl function_id string_idl ping \
	  string1 string2 string3 string4 string5 string6 \
	  string7 string8 \
	  andy1 andy2 andy3 andy4 andy5 andy6 \
	  fpage1 fpage2 pagefault sockets \
	  l4str l4union sort1 init-rcvstring

include $(L4DIR)/mk/subdir.mk
