SYSTEMS			:= 	x86-l4v2
PKGDIR			?=	../../..
L4DIR			?=	$(PKGDIR)/../..

TARGET			 =	libcr7libc.a

SRC_C			 =	libc.c atoi.c qsort.c toupper.c gmtime.c \
				gmtime_r.c localtime.c localtime_r.c mktime.c \
				isleap.c time_table_spd.c io.c

include $(L4DIR)/mk/lib.mk

