PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= lib$(PKGNAME).a libfprov_ext.a
SYSTEMS		= x86-l4v2 arm-l4v2 amd64-l4v2

CLIENTIDL	= $(PKGNAME).idl
CLIENTIDL_libfprov_ext.a = fprov_ext.idl

include $(L4DIR)/mk/lib.mk
