#
# $Id$
#

PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET  = logex_t1 logex_t2
DEFAULT_RELOC_logex_t1 = 0x00980000
DEFAULT_RELOC_logex_t2 = 0x00a00000
MODE    = sigma0
SRC_C   = l4.c
LIBS    = -llog

include $(L4DIR)/mk/prog.mk
