#define CONFIG_NAME "L4IDE"
#define CONFIG_VERSION (100)
#define CONFIG_DATE "2003-11-17"

/*
 * L4IDE driver
 */
#define CONFIG_L4IDE_DEBUG_MSG 0
#define CONFIG_L4IDE_DEBUG_COMMAND 0
#define CONFIG_L4IDE_DEBUG_NOTIFY 0
#define CONFIG_L4IDE_MAX_CLIENTS (4)

/*
 * Threads
 */
#define CONFIG_L4IDE_MAX_THREADS (64)
#define CONFIG_L4IDE_THREAD_BASE (24)
#define CONFIG_L4IDE_COMMAND_STACK_SIZE (65536)
#define CONFIG_L4IDE_CMD_PRIO (112)
#define CONFIG_L4IDE_NOTIFY_STACK_SIZE (8192)
#define CONFIG_L4IDE_NOTIFY_PRIO (111)
#define CONFIG_L4IDE_WORK_PRIO (109)

/*
 * Memory / descriptor allocation
 */
#define CONFIG_L4IDE_NUM_REQUESTS (10000/*4096*/)

