PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

SYSTEMS	= x86-l4v2
TARGET	= libomega0.a
SRC_C	= attach.c detach.c internal.c list.c pass.c request.c timeout.c

PRIVATE_INCDIR = $(PKGDIR)/server/include $(PKGDIR)/lib/include

include $(L4DIR)/mk/lib.mk
