#define MEMORY_MODULE "Memory 1.0"
#define PRESENTER_MODULE "Presenter 1.0"
#define SLIDE_MODULE "Slide 1.0"
#define PRESENTATION_MODULE "Presentation 1.0"
#define HASHTAB_MODULE "Hashtable 1.0"
#define ARRAYLIST_MODULE "Arraylist 1.0"
#define KEYGENERATOR_MODULE "Keygenerator 1.0"
#define PRESMANAGER_MODULE "Presmanager 1.0"
#define PRESENTER_SERVER_MODULE "Presenter Server 1.0"
#define PRESENTER_VIEW_MODULE "Presenter View 1.0"
#define DATAPROVIDER_MODULE "Dataprovider Server 1.0"
#define DISPLAY_MODULE "Display Module 1.0"
#define ENCAPL4X_MODULE "EncapL4x Module 1.0"
#define TIMER_MODULE "Timer Module 1.0"
