SYSTEMS			:= 	x86-l4v2
PKGDIR			?=	../../..
L4DIR			?=	$(PKGDIR)/../..

TARGET			=	libprobelib.a

PRIVATE_INCDIR		=	$(PKGDIR)/include $(PKGDIR)/lib/include $(PKGDIR_OBJ)/lib/include

SRC_C			=	probe_mpeg.c probe_wav.c probe_mp3.c probe_avi.c probe_ogm.c

include $(L4DIR)/mk/lib.mk

