PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../../../..

IDL		= $(PKGNAME).idl
IDL_FLAGS	= -T -fforce-corba-alloc -ftestsuite-shutdown -ftest-no-success-message
SYSTEMS		= x86-l4v2 x86-l4x0

include $(L4DIR)/mk/idl.mk
