SYSTEMS       := x86-linux
PKGDIR        ?= ../../..
L4DIR         ?= $(PKGDIR)/../..

TARGET         = libpetze.a
PRIVATE_INCDIR = $(PKGDIR)/include \
                 $(IDL_PATH)
SRC_C          = libpetze.c

include $(L4DIR)/mk/lib.mk

