/**
 * Small example to illustrate an asynchronous server.
 */

interface async
{
  /* this is the function, which will be processed 
   * asynchronously
   */
  [allow_reply_only]
  void foo([in] long p1, [out] long* p2);

  /* this function is used to deliver the result of the
   * asynchronous processing.
   * One yould also use another server in the same
   * address space to handle the replies to the clients.
   */
  void notify([in] long p1, [in] long result);
};

