/**
 * Small helper Server to be used by async server.
 */

interface sync
{
  /* This function simply increments the value */
  long foo([in] long p1);

  /* This function receives a message from the
   * async server and will send the result to
   * it later.
   */
  [oneway] 
  void bar([in] long p1);
};

