PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..
IDL 		= l4con.idl stream.idl
SYSTEMS		= x86-l4v2 arm-l4v2

IDL_EXPORT_STUB	= stream.idl l4con.idl
IDL_EXPORT_SKELETON = stream.idl l4con.idl

include $(L4DIR)/mk/idl.mk
