/* -*- c -*- */
/* $Id$ */

/**
 * \file	con/idl/stream/stream.idl
 * \brief	streaming IPC interface for pushing console events to clients
 *
 * \author	Christian Helmuth <ch12@os.inf.tu-dresden.de>
 */

/* (c) 2003 Technische Universitaet Dresden
 * This file is part of DROPS, which is distributed under the terms of the
 * GNU General Public License 2. Please see the COPYING file for details. */

/** time value */
typedef struct stream_io_timeval
{
  long tv_sec;
  long tv_usec;
} stream_io_timeval_t;

/** event type */
typedef struct stream_io_input_event
{
  stream_io_timeval_t time;  /* not used */
  unsigned short type;
  unsigned short code;
  unsigned long value;
} stream_io_input_event_t;

/** stream interface */
library stream
{
  /** Stream interface
   * \defgroup idl_stream_if Console Client Stream Interface */
  interface io
    {
      /** Push console event to client
       * \ingroup idl_stream_if
       *
       * \param event		event to push */
      void push([in] stream_io_input_event_t event);
    };
};

