PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

SYSTEMS		= x86-l4v2
DEFAULT_RELOC	= 0x2000000

TARGET		= qt3_thread_test
MODE		= l4env_base

SRC_CC		= main.cc

include $(PKGDIR)/mk/qt3.mk
include $(L4DIR)/mk/prog.mk
