PKGDIR         ?= ../..
L4DIR          ?= $(PKGDIR)/../..
TARGET          = presloader
DEFAULT_RELOC	= 0x590000
MODE		= l4env
SRC_C		= presloader.c
CLIENTIDL	= presenter.idl

include $(L4DIR)/mk/prog.mk
