PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of you package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = signal_example signal_example2 sigalarm_test signalfpe sig_exc_problem

include $(L4DIR)/mk/subdir.mk


