PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

SYSTEMS   := x86-l4v2
TARGET	  = lib$(PKGNAME)-client.a
SRC_C	  = encap.c
CLIENTIDL = stpm.idl
WARNINGS  = -Wall -Wstrict-prototypes

include $(L4DIR)/mk/lib.mk
