# directories we need to know
PKGDIR		= ../..
L4DIR		?= $(PKGDIR)/../..

# no targets, we only use well known subdirs
TARGET = avilib ogmlib probe libavformat
#examples
# include subdir role
include $(L4DIR)/mk/subdir.mk
