# directories we need to know
PKGDIR ?=	..
L4DIR ?=	$(PKGDIR)/../..

# source files
IDL =		blk.idl
SYSTEMS =	x86-l4v2 x86-l4x0
IDL_EXPORT_STUB = blk.idl
IDL_EXPORT_SKELETON = blk.idl
IDL_FLAGS =	-fl4types -fconst-as-define -fserver-parameter

# include IDL role
include $(L4DIR)/mk/idl.mk

