# directories we need to know
PKGDIR ?=	..
L4DIR ?=	$(PKGDIR)/../..

# source files
IDL =		blk.idl
IDL_TYPE =	flick
SYSTEMS =	x86-l4v2 x86-l4x0
IDL_EXPORT_STUB = blk.idl
IDL_EXPORT_SKELETON = blk.idl

# include IDL role
include $(L4DIR)/mk/idl.mk

