# directories we need to know
PKGDIR ?=	..
L4DIR ?=	$(PKGDIR)/../..

# source files
IDL =		blk.idl
SYSTEMS =	x86-l4v2
IDL_EXPORT_STUB = blk.idl
IDL_EXPORT_SKELETON = blk.idl
IDL_FLAGS =	-fconst-as-define

# include IDL role
include $(L4DIR)/mk/idl.mk

