# directories we need to know
PKGDIR ?=	../..
L4DIR ?=	$(PKGDIR)/../..

# source files
SRC_C =		main.c
MODE =		sigma0

# target
TARGET =	llist
DEFAULT_RELOC	= 0x9a0000
SYSTEMS = 	x86-l4v2

include $(L4DIR)/mk/prog.mk

