# directories we need to know
PKGDIR ?= ../..
L4DIR  ?=  $(PKGDIR)/../..

SYSTEMS = x86-l4v2 x86-l4x0

SRC_C   = tree_helper.c paths.c

MODE    = l4env_minimal

TARGET  = libl4vfs_tree_helper.a

# include lib role
include $(L4DIR)/mk/lib.mk
