/* -*- c -*- */ 
import <l4/sys/types.h>
import <l4/dietlibc/io-types.h>

library io
{
    [uuid(1002), abstract]
    interface attachable
    {
        /* mount some dir of a volume to some other point in the namespace
         * mounted_dir is a path relative to the volume's root
         *   (e.g. "/", "/dev", "/abc")
         * mount_dir is a path relative to the name-space's root
         *   (e.g. "/linux", "/l4/server")
         */
        int           attach_namespace([in] volume_id_t volume_id,
                                       [in, string] char * mounted_dir,
                                       [in, string] char * mount_dir);

        // unmount some dir from the namespace
        int           deattach_namespace([in, string] char * mount_dir);
    };
};
