import <l4/sys/types.h>
import <l4/dm_generic/types.h>

library l4x
{
	interface exec {
	
	int execvp ([in, string]	char* command_path,
   				[in, string]	char** argv,
				[in]			l4dm_dataspace_t *src_ds,
				[out]			l4dm_dataspace_t *dest_ds);
	};

};


