/* -*- c -*- */ 
import <l4/sys/types.h>
import <l4/dietlibc/io-types.h>

import "basic_name_server.idl"
import "name_space_provider.idl"
import "attachable.idl"
import "basic_io.idl"

library io
{
    [uuid(1003)]
    interface object_server : basic_name_server, basic_io
    {
    };
};
