/* -*- c -*- */ 
import <sys/stat.h>
import <sys/types.h>
import <fcntl.h>
import <dirent.h>

import <l4/sys/types.h>
import <l4/dietlibc/io-types.h>

library io
{
    [uuid(51)]
    interface rw
    {
        ssize_t         read([in] object_handle_t fd,
                             [out, size_is(count), ref, prealloc] char **buf,
                             [in, out] size_t *count);
        ssize_t         write([in] object_handle_t fd,
                              [in, prealloc, ref, size_is(count)] char *buf,
                              [in, out] size_t *count);
    };
};
