SYSTEMS         := x86-l4v2
PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..
MODE             = l4linux
TARGET           = lxevent
SRC_C            = main.c
LIBS             = -ll4ovlinput
PRIVATE_INCDIR   = $(PKGDIR)/include

include $(L4DIR)/mk/prog.mk
