PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

TARGET    = libore.a
SYSTEMS   = x86-l4v2 x86-l4x0
SRC_C     = lib.c open.c rx_string.c tx_string.c close.c debug.c
CLIENTIDL = ore.idl

include $(L4DIR)/mk/lib.mk
