# directories we need to know
PKGDIR 		?= ../..
L4DIR		?= $(PKGDIR)/../..

# source files
SRC_C		= main.c

# target
TARGET		= load
LIBS		= -lparsecmdline
MODE		= linux
PRIVATE_INCDIR	= $(L4INCDIR)

include $(L4DIR)/mk/prog.mk
