/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define TUNECPU generic
#define HAVE_MMX 1
#define __CPU__ 586
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1
#define restrict __restrict__

#include "../../../config/verner_config.h"

#if BUILD_libavcodec_encoder
#define CONFIG_ENCODERS 1
#else
#define CONFIG_ENCODERS 0
#endif
#if BUILD_libavcodec_decoder
#define CONFIG_DECODERS 1
#else
#define CONFIG_DECODERS 0
#endif
#if BUILD_libavcodec_risky
#define CONFIG_RISKY 1
#else
#define CONFIG_RISKY 0
#endif


/* renable to get SSE-Support */
//#define HAVE_BUILTIN_VECTOR 1
